import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// This defines the visual layout of the exported PDF — used server-side
// in the export-pdf API route, rendered to a PDF buffer and streamed
// back to the browser as a download. Pro feature.

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24, borderBottom: '2pt solid #185FA5', paddingBottom: 12 },
  brand: { fontSize: 16, fontWeight: 700, color: '#0C447C' },
  date: { fontSize: 9, color: '#666' },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4, color: '#1a1a1a' },
  subtitle: { fontSize: 10, color: '#666', marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 11, fontWeight: 700, color: '#0C447C', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottom: '0.5pt solid #e5e5e5' },
  rowLabel: { color: '#444' },
  rowValue: { fontWeight: 700, color: '#1a1a1a' },
  resultBox: { backgroundColor: '#E6F1FB', padding: 16, borderRadius: 4, marginBottom: 16 },
  resultValue: { fontSize: 24, fontWeight: 700, color: '#0C447C' },
  resultInterpretation: { fontSize: 11, color: '#1a1a1a', marginTop: 8, lineHeight: 1.5 },
  patientField: { fontSize: 10, color: '#444', marginBottom: 4 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#999', borderTop: '0.5pt solid #e5e5e5', paddingTop: 8 },
  signatureLine: { marginTop: 40, borderTop: '0.5pt solid #999', width: 200, paddingTop: 4, fontSize: 9, color: '#666' },
});

interface CalculationPDFProps {
  calculatorName: string;
  patientLabel?: string;
  inputs: Record<string, any>;
  result: { value: string | number; unit?: string; interpretation: string };
  clinicianName?: string;
  generatedAt: string;
}

export function CalculationPDF({ calculatorName, patientLabel, inputs, result, clinicianName, generatedAt }: CalculationPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>MedCalc Pro</Text>
          <Text style={styles.date}>{generatedAt}</Text>
        </View>

        <Text style={styles.title}>{calculatorName}</Text>
        <Text style={styles.subtitle}>Clinical calculation report</Text>

        {patientLabel ? <Text style={styles.patientField}>Patient/Record reference: {patientLabel}</Text> : null}
        {clinicianName ? <Text style={styles.patientField}>Clinician: {clinicianName}</Text> : null}

        <View style={styles.resultBox}>
          <Text style={styles.resultValue}>
            {result.value} {result.unit || ''}
          </Text>
          <Text style={styles.resultInterpretation}>{result.interpretation}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Inputs used</Text>
          {Object.entries(inputs).map(([key, value]) => (
            <View style={styles.row} key={key}>
              <Text style={styles.rowLabel}>{key}</Text>
              <Text style={styles.rowValue}>{String(value)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.signatureLine}>
          <Text>Clinician signature</Text>
        </View>

        <Text style={styles.footer}>
          Generated by MedCalc Pro. This report is a calculation aid only and does not replace clinical judgement.
          Always verify results against current local guidelines before acting on them.
        </Text>
      </Page>
    </Document>
  );
}
